name: CI
on:
  push:
    branches: ["main"]
  pull_request:
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        config:
        # [Python version, tox env]
        - ["2.7",  "py27-plone52"]
        - ["3.6",  "py36-plone52"]
        - ["3.7",  "py37-plone52"]
        - ["3.8",  "py38-plone52"]
        - ["3.7",  "py37-plone60"]
        - ["3.8",  "py38-plone60"]
        - ["3.9",  "py39-plone60"]
        - ["3.10",  "py310-plone60"]
    name: ${{ matrix.config[1] }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config[0] }}
    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.config[0] }}-${{ hashFiles('setup.*', 'tox.ini') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.config[0] }}-
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test
      run: tox -e ${{ matrix.config[1] }}
